baseurl = "http://primalpond.com/"
languageCode = "en"
title = "primal pond"
author = "d3alek"

[params]
logo      = "/images/logo.jpg"
copyright = "d3alek All rights reserved."
twitter   = "https://twitter.com/d3alek"
facebook  = "https://www.facebook.com/akodzhabashev"
github    = "https://github.com/d3alek/"
email     = "akodzhabashev@gmail.com"
analytics = "UA-64684947-2"
disqusShortname = "primalpond"

